/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netflix_luismontalvan;

/**
 *
 * @author luxte
 */
public class NetflixStartUp extends javax.swing.JFrame {

    /**
     * Creates new form Netflix
     */
    public NetflixStartUp() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jPuserScreen.setMaximumSize(this.getSize());
        jpbStartUp.setVisible(false);
        jPuserScreen.setVisible(false);
//       LoadingScreen ls = new LoadingScreen(jpbStartUp, true, true, jPstartUp);
        //Thread carga = new Thread(ls);
        LoadingScreen ls = new LoadingScreen(jpbStartUp, true, true, jPstartUp, jPuserScreen);
        ls.start();
        User2.setVisible(false);
        User3.setVisible(false);
        User4.setVisible(false);
        User6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPstartUp = new javax.swing.JPanel();
        jLNetflixInicio = new javax.swing.JLabel();
        jpbStartUp = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPuserScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        User1 = new javax.swing.JButton();
        jLUser1 = new javax.swing.JLabel();
        User2 = new javax.swing.JButton();
        User3 = new javax.swing.JButton();
        User4 = new javax.swing.JButton();
        User5 = new javax.swing.JButton();
        User6 = new javax.swing.JButton();
        jPNetflixHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPstartUp.setBackground(new java.awt.Color(0, 0, 0));
        jPstartUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNetflixInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix_luismontalvan/wp5063339.png"))); // NOI18N
        jPstartUp.add(jLNetflixInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 640, 220));
        jPstartUp.add(jpbStartUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel2.setText("jLabel2");
        jPstartUp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15670, 16570, -1, -1));

        jPuserScreen.setBackground(new java.awt.Color(0, 0, 0));
        jPuserScreen.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPuserScreen.setMinimumSize(new java.awt.Dimension(1230, 580));
        jPuserScreen.setPreferredSize(new java.awt.Dimension(15704, 16585));
        jPuserScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Whos Watching");
        jPuserScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32767, 32767, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Who's Watching? ");
        jPuserScreen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 210, -1));

        User1.setBackground(new java.awt.Color(0, 0, 0));
        User1.setIcon(new javax.swing.ImageIcon("C:\\Users\\luxte\\Documents\\Netflix\\pngwing.com.png")); // NOI18N
        jPuserScreen.add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 200, 190));

        jLUser1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLUser1.setForeground(new java.awt.Color(204, 204, 204));
        jLUser1.setText("Yo");
        jPuserScreen.add(jLUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, -1, -1));

        User2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix_luismontalvan/2.png"))); // NOI18N
        jPuserScreen.add(User2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 200, 190));

        User3.setIcon(new javax.swing.ImageIcon("C:\\Users\\luxte\\Documents\\Netflix\\3.png")); // NOI18N
        jPuserScreen.add(User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 200, 190));

        User4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netflix_luismontalvan/5.png"))); // NOI18N
        jPuserScreen.add(User4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 200, 190));

        User5.setIcon(new javax.swing.ImageIcon("C:\\Users\\luxte\\Documents\\Netflix\\1.png")); // NOI18N
        jPuserScreen.add(User5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 200, 190));

        User6.setIcon(new javax.swing.ImageIcon("C:\\Users\\luxte\\Documents\\Netflix\\4.png")); // NOI18N
        jPuserScreen.add(User6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 200, 190));

        javax.swing.GroupLayout jPNetflixHomeLayout = new javax.swing.GroupLayout(jPNetflixHome);
        jPNetflixHome.setLayout(jPNetflixHomeLayout);
        jPNetflixHomeLayout.setHorizontalGroup(
            jPNetflixHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPNetflixHomeLayout.setVerticalGroup(
            jPNetflixHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPstartUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPuserScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPNetflixHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPstartUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPuserScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPNetflixHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetflixStartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetflixStartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetflixStartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetflixStartUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetflixStartUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton User1;
    private javax.swing.JButton User2;
    private javax.swing.JButton User3;
    private javax.swing.JButton User4;
    private javax.swing.JButton User5;
    private javax.swing.JButton User6;
    private javax.swing.JLabel jLNetflixInicio;
    private javax.swing.JLabel jLUser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPNetflixHome;
    private javax.swing.JPanel jPstartUp;
    private javax.swing.JPanel jPuserScreen;
    private javax.swing.JProgressBar jpbStartUp;
    // End of variables declaration//GEN-END:variables
    LoadingScreen ls;
}
